### PR TITLE
Feat/#1 make web app UI responsive

### PR DESCRIPTION
**Pull request by Marcjazz**
I'm almost done with this issue #1 
@N-45div pull and see what has change

### CODE REVIEW

**Comment by N-45div** [comment]
The home page is still not responsive but overall great work on other page @Marcjazz 
image

**Comment by N-45div** [comment]
Should i merge the changes till now ? or I should wait for the home page work @Marcjazz

**Comment by Marcjazz** [comment]
> Should i merge the changes till now ? or I should wait for the home page work @Marcjazz

My bad, last minutes changes. Wait for it

**Comment by N-45div** [comment]
Any changes made in the repo tag me here i might not be available in discord I will be able to reply back to you here 

Thank you

**Comment by Marcjazz** [comment]
> Any changes made in the repo tag me here i might not be available in discord I will be able to reply back to you here
> 
> Thank you

Please checkout the new updates

**Comment by N-45div** [comment]
> > Any changes made in the repo tag me here i might not be available in discord I will be able to reply back to you here
> > Thank you
> 
> Please checkout the new updates

image
I am getting this buddy .....

**Comment by Marcjazz** [comment]
> > > Any changes made in the repo tag me here i might not be available in discord I will be able to reply back to you here
> > > Thank you
> > 
> > 
> > Please checkout the new updates
> 
> image I am getting this buddy .....

I had the same issues but after clearing my cache it worked

**Comment by N-45div** [comment]
> > > > Any changes made in the repo tag me here i might not be available in discord I will be able to reply back to you here
> > > > Thank you
> > > 
> > > 
> > > Please checkout the new updates
> > 
> > image I am getting this buddy .....
> 
> I had the same issues but after clearing my cache it worked

Yes it worked 👍 ! Will merge the code now

**Comment by Marcjazz** [comment]
Also

> > > > Any changes made in the repo tag me here i might not be available in discord I will be able to reply back to you here
> > > > Thank you
> > > 
> > > 
> > > Please checkout the new updates
> > 
> > 
> > image I am getting this buddy .....
> 
> I had the same issues but after clearing my cache it worked

Also check that everything still works well

**Comment by Marcjazz** [comment]
Have you been able to install the app

**Comment by N-45div** [comment]
> Also
> 
> > > > > Any changes made in the repo tag me here i might not be available in discord I will be able to reply back to you here
> > > > > Thank you
> > > > 
> > > > 
> > > > Please checkout the new updates
> > > 
> > > 
> > > image I am getting this buddy .....
> > 
> > I had the same issues but after clearing my cache it worked
> 
> Also check that everything still works well

Fine

**Comment by N-45div** [comment]
> Have you been able to install the app
> 

I will see this but the application is working fine but as we need to work on rust and wormhole that will be the backend...

**Comment by N-45div** [comment]
Type error: Type 'OmitWithTag<typeof import("C:/Users/Suresh Babu/weaveapp/weaveapp/src/app/lend/page"), "default" | "metadata" | "config" | "generateStaticParams" | "revalidate" | "dynamic" | "dynamicParams" | ... 6 more ... | "generateViewport", "">' does not satisfy the constraint '{ [x: string]: never; }'.
  Property 'getColumns' is incompatible with index signature.
    Type '() => ColumnDef<Asset>[]' is not assignable to type 'never'.

   6 |
   7 | // Check that the entry is a valid entry
>  8 | checkFields<Diff<{
     |             ^
   9 |   default: Function
  10 |   config?: {}
  11 |   generateStaticParams?: Function  

I am getting this error while npm run build do check this out this si the error in vercel @Marcjazz

**Comment by Marcjazz** [comment]
> Type error: Type 'OmitWithTag<typeof import("C:/Users/Suresh Babu/weaveapp/weaveapp/src/app/lend/page"), "default" | "metadata" | "config" | "generateStaticParams" | "revalidate" | "dynamic" | "dynamicParams" | ... 6 more ... | "generateViewport", "">' does not satisfy the constraint '{ [x: string]: never; }'. Property 'getColumns' is incompatible with index signature. Type '() => ColumnDef[]' is not assignable to type 'never'.
> 
> 6 | 7 | // Check that the entry is a valid entry
> 
> > 8 | checkFields<Diff<{
> > |             ^
> > 9 |   default: Function
> > 10 |   config?: {}
> > 11 |   generateStaticParams?: Function
> 
> I am getting this error while npm run build do check this out this si the error in vercel @Marcjazz

I've fixed the changes

**Comment by Marcjazz** [comment]
> > Have you been able to install the app
> 
> I will see this but the application is working fine but as we need to work on rust and wormhole that will be the backend...the functionality is same as before
> 
> @Marcjazz I think we need to deploy on vercel to check PWA installation I need to deploy on that

image

You can install the app with the first icon on the right

**Comment by N-45div** [comment]
Fine buddy i am able to install the App also

**Review by N-45div — COMMENTED** [review]
Reviewed All the things

**Pull request merged**
